### PR TITLE
Add system definition file

### PR DESCRIPTION
**Pull request by thomp**
Might make it easier to incorporate into other projects or, down the road, into quicklisp

### CODE REVIEW

**Comment by spyrosoft** [comment]
I've never done that before. Do you have any resources I could use to do so?

**Comment by thomp** [comment]
The quicklisp FAQ ( https://www.quicklisp.org/beta/faq.html ) has good information on getting the library into quicklisp. If you're just interested in how .asd files are used, the ASDF manual ( https://common-lisp.net/project/asdf/asdf.html#Using-ASDF ) has more information than most mere mortals are likely to use. If you're wondering about how quicklisp and a local project interact... as long as ASDF is happily installed on your lisp and if quicklisp is configured, a local project can be put into ~/quicklisp/local-projects to make it accessible to quicklisp. Hope that helps...

**Comment by spyrosoft** [comment]
Awesome. Thank you. I've wanted to do this for some time. When I cracked open the source code of another package to see how they did it, it was pretty intimidating and I never made the effort.

**Comment by thomp** [comment]
Systems have been one of Common Lisp's weaker spots for years (a long-time lisper offers clarification on the jargon a bit at  http://weitz.de/packages.html ). Things have improved in the past few years with quicklisp and ASDF3 ( http://fare.tunes.org/files/asdf3/asdf3-2014.html ).

**Comment by spyrosoft** [comment]
For some reason I thought this was an issue, not a pull request. Otherwise I would have accepted right away. Thank you for contributing!

**Pull request merged**
